### ISSUE TITLE
gcpbuilds failure: cannot read property REPO_NAME

### ISSUE THREAD

**Issue by aabedraba** [kevinsimper/gcphelp-cli#3]
Error message: 
```
Fetching latest builds
(node:19872) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'REPO_NAME' of undefined
    at /home/aabedraba/.nvm/versions/node/v14.3.0/lib/node_modules/gcphelp/dist/builds.js:20:67
    at Array.map (<anonymous>)
    at main (/home/aabedraba/.nvm/versions/node/v14.3.0/lib/node_modules/gcphelp/dist/builds.js:18:32)
    at Object.<anonymous> (/home/aabedraba/.nvm/versions/node/v14.3.0/lib/node_modules/gcphelp/dist/builds.js:37:5)
```
Replicate:
 - Change GCP account with `gcpacaccount`, set a new project
 - Change back to original account, set the original project
 - `gcpbuilds`

**Comment by aabedraba** [comment]
The problem isn't persisting anymore...
